/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['type/url.js']) {
  _$jscoverage['type/url.js'] = [];
  _$jscoverage['type/url.js'][1] = 0;
  _$jscoverage['type/url.js'][2] = 0;
  _$jscoverage['type/url.js'][3] = 0;
  _$jscoverage['type/url.js'][4] = 0;
  _$jscoverage['type/url.js'][5] = 0;
  _$jscoverage['type/url.js'][14] = 0;
  _$jscoverage['type/url.js'][15] = 0;
  _$jscoverage['type/url.js'][19] = 0;
  _$jscoverage['type/url.js'][20] = 0;
  _$jscoverage['type/url.js'][22] = 0;
  _$jscoverage['type/url.js'][23] = 0;
  _$jscoverage['type/url.js'][27] = 0;
  _$jscoverage['type/url.js'][28] = 0;
  _$jscoverage['type/url.js'][30] = 0;
  _$jscoverage['type/url.js'][33] = 0;
  _$jscoverage['type/url.js'][36] = 0;
  _$jscoverage['type/url.js'][38] = 0;
  _$jscoverage['type/url.js'][41] = 0;
}
_$jscoverage['type/url.js'][1]++;
var Utils = require("../utils");
_$jscoverage['type/url.js'][2]++;
var TypeFactory = require("./base").TypeFactory;
_$jscoverage['type/url.js'][3]++;
var CondenseError = require("./base").CondenseError;
_$jscoverage['type/url.js'][4]++;
var Validator = require("validator");
_$jscoverage['type/url.js'][5]++;
var UrlType;
_$jscoverage['type/url.js'][14]++;
UrlType = (function () {
  _$jscoverage['type/url.js'][15]++;
  var defaults = {};
  _$jscoverage['type/url.js'][19]++;
  UrlType = (function (n) {
  _$jscoverage['type/url.js'][20]++;
  var o = new String(n);
  _$jscoverage['type/url.js'][22]++;
  o.validate = (function (options) {
  _$jscoverage['type/url.js'][23]++;
  options = Utils.merge(Utils.clone(defaults), options);
  _$jscoverage['type/url.js'][27]++;
  var url = this.toString();
  _$jscoverage['type/url.js'][28]++;
  var check = Validator.check(url);
  _$jscoverage['type/url.js'][30]++;
  return CondenseError(check.isUrl, check);
});
  _$jscoverage['type/url.js'][33]++;
  return o;
});
  _$jscoverage['type/url.js'][36]++;
  UrlType.__name = "Url";
  _$jscoverage['type/url.js'][38]++;
  return UrlType;
})();
_$jscoverage['type/url.js'][41]++;
module.exports = UrlType;
_$jscoverage['type/url.js'].source = ["var Utils = require(\"../utils\");","var TypeFactory = require(\"./base\").TypeFactory;","var CondenseError = require(\"./base\").CondenseError;","var Validator = require('validator');","var UrlType;","","/*"," *"," * Usage:"," *   var UrlType = Types.get(\"Url\");"," *   var x = UrlType(100);"," *"," */","UrlType = (function(){","  var defaults = {","    // required: true,","  }","  ","  UrlType = function(n){","    var o = new String(n);","    ","    o.validate = function(options){","      options = Utils.merge(Utils.clone(defaults), options);","      ","      // TODO: validate options obj","      ","      var url = this.toString();","      var check = Validator.check(url);","      ","      return CondenseError(check.isUrl, check);","    }","    ","    return o;","  }","  ","  UrlType.__name = \"Url\";","  ","  return UrlType;","})();","","module.exports = UrlType;"];
